name: test

on: push

jobs:
  test:
    name: Test django-saml2-auth
    runs-on: ubuntu-latest
    strategy:
      matrix:
        versions:
          - { "djangoVersion": "2.2.27", "pythonVersion": "3.7" }
          - { "djangoVersion": "2.2.27", "pythonVersion": "3.8" }
          - { "djangoVersion": "2.2.27", "pythonVersion": "3.9" }
          - { "djangoVersion": "2.2.27", "pythonVersion": "3.10" }
          - { "djangoVersion": "3.2.12", "pythonVersion": "3.7" }
          - { "djangoVersion": "3.2.12", "pythonVersion": "3.8" }
          - { "djangoVersion": "3.2.12", "pythonVersion": "3.9" }
          - { "djangoVersion": "3.2.12", "pythonVersion": "3.10" }
          - { "djangoVersion": "4.0.3", "pythonVersion": "3.8" }
          - { "djangoVersion": "4.0.3", "pythonVersion": "3.9" }
          - { "djangoVersion": "4.0.3", "pythonVersion": "3.10" }
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.versions.pythonVersion }}
      - name: Install xmlsec1
        run: sudo apt-get install xmlsec1
      - name: Install dependencies
        run: pip install -r requirements_test.txt && pip install -e .
      - name: Install Django ${{ matrix.versions.djangoVersion }}
        run: pip install Django==${{ matrix.versions.djangoVersion }}
      - name: Test Django ${{ matrix.versions.djangoVersion }}
        run: pytest .
